[target.thumbv6m-none-eabi]
runner = "probe-run --chip STM32G030J6Mx"

rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"